#!/data/data/com.termux/files/usr/bin/python
import platform,os
#####
os.system("git pull")
bit = platform.architecture()[0]
if bit == '64bit':
    import AUTO_CREATE
elif bit == '32bit':
    print('\033[1;97m[🔴❌🔴] SORRY BROTHER YOUR DEVIS IS 32 BIT ')
 
